### PR TITLE
Bug: Catch any underlying exceptions from http.HTTPException

### PR DESCRIPTION
**Pull request by Poogles**
Resolves https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2/issues/6

### CODE REVIEW

**Comment by Poogles** [comment]
Oops, commit name doesn't match mine.  Will fix later.

**Comment by jonparrott** [comment]
So, `AuthorizedHttp.request` *shouldn't* wrap exceptions at all. It should behave *exactly* like the thing it's wrapping. Conversely, `Request` *should* wrap exceptions. The difference here is that `AuthorizedHttp` is supposed to be a user-facing replacement for `httplib2.Http` and should more or less stick to the substitution principle, whereas `Request` is an internal facing construct that allows this library to be framework agnostic.

**Comment by Poogles** [comment]
@jonparrott cheers for that.  I saw it but seemingly ignored it in a rush to leave.  That should now be fixed and I've changed the git user.name to one that should have signed the SLA (afaik).

**Comment by jonparrott** [comment]
LGTM, but you'll need to please travis.

**Comment by Poogles** [comment]
Travis now passes, you might want to check what I've done though.  Rather than adding a unit test for an import error I've just added six to the requirements and fetched through there.  Given that pretty much everything that targets 2/3 bundles six anyway it seems like the easiest thing?

CLA should pass now (how is it rerun?).

**Comment by jonparrott** [comment]
Thank you, @Poogles!

**Pull request merged**
